import type { Metadata } from 'next'
import '@/app/globals.css'
import CssBaseline from '@mui/material/CssBaseline';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
    title: '城轨数据中台',
    description: 'Generated by 城轨事业部精益信息化组',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="zh">
            <body className={`antialiased`}>
                <CssBaseline />
                {children}
            </body>
        </html>
    )
}
